version: '3.7'

services:
  elasticsearch:
    build:
      context: ./elasticSearch
      dockerfile: Dockerfile
    image: es
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Adjust JVM heap size as needed
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - network.host=0.0.0.0
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    image: ls
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
    ports:
      - "5044:5044"
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m  # Adjust JVM heap size as needed
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
    image: kib
    container_name: kibana
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/kibana.yml
    environment:
      - server.host=0.0.0.0
      - server.shutdownTimeout=5s
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=trial
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  es_data:
    driver: local

networks:
  elk:
    driver: bridge
